import httpx

BASE_URL = "http://127.0.0.1:8081"
HEADERS = {"Authorization": "Bearer demo-token-full_test_user"}

def test_full_platform():
    # Restart app with fresh imports
    with httpx.Client(base_url=BASE_URL, timeout=15.0) as client:
        # 1. Health
        res = client.get("/api/health")
        assert res.status_code == 200
        print("✓ Health OK")

        # 2. Seed Demo
        res = client.post("/api/demo/seed", headers=HEADERS)
        assert res.status_code == 200
        print("✓ Seed Demo OK")

        # 3. Autopilot Run Now (Phase 3)
        res = client.post("/api/autopilot/run-now", headers=HEADERS)
        assert res.status_code == 200
        data = res.json()
        assert data.get("status") == "success"
        print(f"✓ Autopilot Run Now OK (Alerts: {data['result']['alerts_created']})")

        # 4. Check Alerts & Briefs generated by Autopilot
        res = client.get("/api/alerts", headers=HEADERS)
        assert res.status_code == 200
        alerts = res.json()
        assert len(alerts) > 0
        print(f"✓ Autopilot Alerts Verified ({len(alerts)} alerts generated)")

        res = client.get("/api/briefs", headers=HEADERS)
        assert res.status_code == 200
        briefs = res.json()
        assert len(briefs) > 0
        print(f"✓ Autopilot Briefs Verified ({len(briefs)} briefs generated)")

        # 5. Learn Library (Phase 5)
        res = client.get("/api/learn/lessons", headers=HEADERS)
        assert res.status_code == 200
        lessons = res.json()
        assert len(lessons) >= 10
        print(f"✓ Learn Library Verified ({len(lessons)} comprehensive lessons)")

        # 6. Life Mode Game (Phase 4)
        res = client.get("/api/game/chapters/1", headers=HEADERS)
        assert res.status_code == 200
        ch1 = res.json()
        assert ch1["chapter_index"] == 1
        assert len(ch1["choices"]) >= 2
        print(f"✓ Life Mode Chapter 1 Verified ('{ch1['title']}')")

        # 7. Life Mode End Report
        res = client.post("/api/game/end-report", headers=HEADERS, json={
            "timeline": [
                {"chapter_index": 1, "choice_id": "fund_emergency"},
                {"chapter_index": 2, "choice_id": "itemized_bill_hsa"},
                {"chapter_index": 4, "choice_id": "pass_scam"},
                {"chapter_index": 5, "choice_id": "maximize_match"}
            ],
            "initial_stats": {"cash": 5000.0, "debt": 1500.0}
        })
        assert res.status_code == 200
        rep = res.json()
        assert "decision_score" in rep and "achievements" in rep
        print(f"✓ Life Mode Report Verified (Score: {rep['decision_score']}, Grade: {rep['grade']})")

        # 8. Assistant Chat (Context-Aware Multi-Agent Routing)
        res = client.post("/api/assistant/chat", headers=HEADERS, json={
            "prompt": "Which of my trials should I cancel?",
            "page": "trials"
        })
        assert res.status_code == 200
        chat_resp = res.json()
        assert "Trial Guard" in chat_resp["reply"]
        print("✓ AI Assistant Chat Verified:", chat_resp["reply"][:60], "...")

        print("\nALL BACKEND PHASES (1, 2, 3, 4, 5, 6) INTEGRATION TESTS PASSED!")

if __name__ == "__main__":
    test_full_platform()
